---
abstract: 'Audit log for authentication/authorization'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  File::HomeDir::Test: 0
  Test::Mojo: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300021, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PlugAuth-Plugin-Audit
requires:
  DateTime: 0
  File::HomeDir: 0
  Path::Class::Dir: 0
  Path::Class::File: 0
  PlugAuth: 0.09
  PlugAuth::Role::Plugin: 0
  Role::Tiny::With: 0
  YAML::XS: 0
  perl: v5.10.0
resources:
  bugtracker: https://github.com/plicease/plugauth-plugin-audit/issues
  homepage: http://perl.wdlabs.com/PlugAuth-Plugin-Audit/
  repository: git://github.com/plicease/plugauth-plugin-audit.git
version: 0.05
